djecommerce/core/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name= 'home'),
    path('search', views.search, name='search'),
    path('category-list', views.category_list, name= 'category-list'),
    path('brand-list', views.brand_list, name= 'brand-list'),
    path('product-list', views.product_list, name= 'product-list'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

djecommerce/djecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

djecommerce/core/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
# Below that are models

# Banner 
class Banner(models.Model):
    img = models.CharField(max_length=200)
    alt_text = models.CharField(max_length=300)
    class Meta:
        verbose_name_plural = '1. Banners'
# Category
class Category(models.Model):
    title = models.CharField(max_length = 100)
    image = models.ImageField(upload_to="cat_imgs/")
    
    class Meta:
        verbose_name_plural = '2. Categories'
    def image_tag(self):
        return mark_safe('<img src= "%s" width="50" height = "50" />' % (self.image.url))
    def __str__(self):
        return self.title
# Brand
class Brand(models.Model):
    title = models.CharField(max_length = 100)
    image = models.ImageField(upload_to="brand_imgs/")
    class Meta:
        verbose_name_plural = '3. Brands'
    def __str__(self):
        return self.title
# Color
class Color(models.Model):
    title = models.CharField(max_length = 100)
    color_code = models.CharField(max_length = 100)
    class Meta:
        verbose_name_plural = '4. Colors'
    def color_bg(self):
        return mark_safe('<div style = "width:30px; height:30px; background-color:%s"></div>' % (self.color_code))
    def __str__(self):
        return self.title
# Size
class Size(models.Model):
    title = models.CharField(max_length = 100)
    class Meta:
        verbose_name_plural = '5. Sizes'
    def __str__(self):
        return self.title
# Product model
class Product(models.Model):
    title = models.CharField(max_length = 200)
    image = models.ImageField(upload_to="product_imgs/")
    slug = models.CharField(max_length = 400)
    detail = models.TextField()
    specs = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    class Meta:
        verbose_name_plural = '6. Products'
    def __str__(self):
        return self.title

# Product Attribute
class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    price = models.PositiveBigIntegerField()
    class Meta:
        verbose_name_plural = '7. ProductAttributes'
    def __str__(self):
        return self.product.title

# Add some Data Table of Functionality Purchase
# class lưu trữ thông tin địa chỉ
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.street_address}, {self.city}, {self.state} {self.postal_code}"
# class lưu trữ thông tin đơn hàng (ngày đặt hàng, trạng thái,...)
class Order(models.Model):
    PENDING = 0
    APPROVE = 1
    CANCELED = 2

    STATUS_CHOICES = (
        (PENDING, 'Pending'),
        (APPROVE, 'Approve'),
        (CANCELED, 'Canceled'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    shipping_address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=PENDING)

    def __str__(self):
        return f"Order {self.id}"
# thông tin giỏ hàng
class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.title}"
# thông tin sản phẩm
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2) 

# thông tin thanh toán (ví dụ: số thẻ tín dụng, ngày hết hạn, v.v.)
class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment_method = models.CharField(max_length=50)
    
# thông tin voucher
class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    discount_percent = models.DecimalField(max_digits=5, decimal_places=2)
    expiration_date = models.DateField()


djecommerce/core/views.py
from django.shortcuts import render
from .models import Category, Brand, Product, ProductAttribute
# Home Page
def home(request):
    return render(request, 'index.html')
# Category
def category_list(request):
    data = Category.objects.all().order_by('-id')
    return render(request, 'category_list.html', {'data':data})
# Brand 
def brand_list(request):
    data = Brand.objects.all().order_by('-id')
    return render(request, 'brand_list.html', {'data':data})
# Product List
def product_list(request):
    data = Product.objects.all().order_by('-id')
    cats = Product.objects.distinct().values('category__title', 'category__id')
    brands = Product.objects.distinct().values('brand__title', 'brand__id')
    colors = ProductAttribute.objects.distinct().values('color__title', 'color__id', 'color__color_code')
    sizes = ProductAttribute.objects.distinct().values('size__title', 'size__id')
    return render(request, 'product_list.html', 
        {
            'data':data,
            'cats': cats,
            'brands': brands,
            'colors': colors,
            'sizes': sizes,

        }
        )
#search
def search(request):
    q = request.GET['q']
    data  = Product.objects.filter(title_icontains=q).order_by('-id')
    return render(request, 'search.html', {'data': data}) 

djecommerce/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Ecommerce Bootstrap Template</title>
	<!-- Font Awesome -->
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome-free/css/all.min.css' %}" />
	<!-- Bootstrap 4 CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'bs4/bootstrap.min.css' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
	<!-- Bootstrap 4 JS -->
	<script type="text/javascript" src="{% static 'bs4/bootstrap.min.js' %}"></script>
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
		<div class="container">
			<a class="navbar-brand" href="/">Ecommerce Shop</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
				aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<form class="form-inline my-2 my-lg-0" action="/search">
					<div class="input-group">
						<input name="q" type="text" class="form-control" placeholder="search" />
						<div class="input-group-append">
							<button class="btn btn-dark" type="submit" id="button-addon2">Search</button>
						</div>
					</div>
				</form>
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a class="nav-link text-white" href="/">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-white" href="{% url 'category-list' %}">Categories</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-white" href="{% url 'brand-list' %}">Brands</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-white" href="/cart.php"><i class="fa fa-shopping-cart"></i> Cart (2)</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-white" href="/account.php"><i class="fa fa-user"></i> My Account</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	{% block content %}
	{% endblock %}
	<footer class="pt-4 my-md-5 pt-md-5 border-top container">
		<div class="row">
			<div class="col-12 col-md">
				<a href="#">Bottle Shop</a>
				<small class="d-block mb-3 text-muted">&copy; 2017-2020</small>
			</div>
			<div class="col-6 col-md">
				<h5>Features</h5>
				<ul class="list-unstyled text-small">
					<li><a class="text-muted" href="#">Cool stuff</a></li>
					<li><a class="text-muted" href="#">Random feature</a></li>
					<li><a class="text-muted" href="#">Team feature</a></li>
					<li><a class="text-muted" href="#">Stuff for developers</a></li>
					<li><a class="text-muted" href="#">Another one</a></li>
					<li><a class="text-muted" href="#">Last time</a></li>
				</ul>
			</div>
			<div class="col-6 col-md">
				<h5>Resources</h5>
				<ul class="list-unstyled text-small">
					<li><a class="text-muted" href="#">Resource</a></li>
					<li><a class="text-muted" href="#">Resource name</a></li>
					<li><a class="text-muted" href="#">Another resource</a></li>
					<li><a class="text-muted" href="#">Final resource</a></li>
				</ul>
			</div>
			<div class="col-6 col-md">
				<h5>About</h5>
				<ul class="list-unstyled text-small">
					<li><a class="text-muted" href="#">Team</a></li>
					<li><a class="text-muted" href="#">Locations</a></li>
					<li><a class="text-muted" href="#">Privacy</a></li>
					<li><a class="text-muted" href="#">Terms</a></li>
				</ul>
			</div>
		</div>
	</footer>
</body>

</html>

djecommerce/core/templates/brand_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Brands</h3>
	<div class="row">
		{% if data %}
			{% for brand in data %}
			<div class="col-md-3 mb-4">
				<div class="card shadow">
				  <a href="#"><img src="/media/{{brand.image}}" class="card-img-top" alt="{{brand.title}}"/
					></a>
				  <div class="card-body">
				    <h6 class="card-text"><a href="#">{{brand.title}}</a></h6>
				  </div>
				</div>
			</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

djecommerce/core/templates/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Categories</h3>
	<div class="row">
		{% if data %}
			{% for cat in data %}
			<div class="col-md-3 mb-4">
				<div class="card shadow">
				  <a href="#"><img src="/media/{{cat.image}}" class="card-img-top" alt="{{cat.title}}"/
					></a>
				  <div class="card-body">
				    <h6 class="card-text"><a href="#">{{cat.title}}</a></h6>
				  </div>
				</div>
			</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

djecommerce/core/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Home Slider -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static '/media_root/images/banners/1.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static '/media_root/images/banners/2.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static '/media_root/images/banners/3.jpg' %}" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Featured Products</h3>
	<div class="row">
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="/detail.php"><img src="{% static '/media_root/images/1.jpg' %}" class="card-img-top" alt="..."></a>
			  <div class="card-body">
			    <h6 class="card-text"><a href="/detail.php">Shoes 1</a></h6>
			  </div>
			  <div class="card-footer">
			  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
			  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
	</div>
	<p class="my-4 text-center"><a href="{% url 'product-list' %}" class="btn btn-dark btn-sm">All Products <i class="fa fa-long-arrow-alt-right"></i></a></p>
</main>
{% endblock %}

djecommerce/core/templates/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			<h3 class="mb-4 border-bottom pb-1">Filters</h3>
			<!-- Filter 1 -->
			<div class="card mb-4">
				<h6 class="card-header">Colors</h6>
				<div class="list-group list-group-flush">
					{% for color in colors %}
					<li class="list-group-item">
						<input value ="{{color.color__id}}" type="checkbox" />&nbsp;
						<button class="btn" style ="background-color: {{color.color__color_code}}; margin-top: -5px"></button>
					</li>
					{% endfor %}
				</div>
			</div>
			<!-- Filter 2 -->
			<div class="card mb-4">
				<h6 class="card-header">Categories</h6>
				<div class="list-group list-group-flush">
					{% for cat in cats %}
					<li class="list-group-item">
						<input value= "{{cat.category__id}}" type = "checkbox" />&nbsp;
						{{cat.category__title}}
					</li>
					{% endfor %}
				</div>
			</div>
			<!-- Filter 3 -->
			<div class="card mb-4">
				<h6 class="card-header">Brands</h6>
				<div class="list-group list-group-flush">
					{% for brand in brands %}
					<li class="list-group-item">
						<input value = "{{brand.brand__id}}" type="checkbox" />&nbsp;
						{{brand.brand__title}}
					</li>
					{% endfor %}
				</div>
			</div>
			<!-- Filter 3 -->
			<div class="card mb-4">
				<h6 class="card-header">Sizes</h6>
				<div class="list-group list-group-flush">
					{% for size in sizes %}
					<li class="list-group-item">
						<input value= "{{size.size__id}}" type = "checkbox" />&nbsp;
						{{size.size__title}}
					</li>
					{% endfor %}
				</div>
			</div>
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row">
				{% for product in data %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h6 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h6>
					  </div>
					  <div class="card-footer">
					  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><a href="products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p>
		</div>
	</div>
</main>
{% endblock %}

djecommerce/core/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1"><span class="text-muted">Search result for</span> {{request.GET.q}}</h3>
	<div class="row">
		{% for product in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
				<a href="/product/{{product.slug}}/{{product.id}}"><img
						src="/media/{{product.productattribute_set.first.image}}" class="card-img-top"
						alt="{{product.title}}"></a>
				<div class="card-body">
					<h6 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h6>
				</div>
				<div class="card-footer">
					<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
					<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					<span class="float-right">
						4.5/5
						<i class="fa fa-star text-warning"></i>
					</span>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</main>
{% endblock %}